### ISSUE TITLE
Fatal error on score view page

### ISSUE THREAD

**Issue by goldhat** [goldhat/quizmaster#109]
Fatal error: Uncaught Error: Class name must be a valid object or a string in /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/lib/model/QuizMaster_Model_Question.php:299 Stack trace: #0 /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/lib/model/QuizMaster_Model_Question.php(321): QuizMaster_Model_Question->loadAnswerDataSingleChoice(Array) #1 /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/lib/model/QuizMaster_Model_Question.php(348): QuizMaster_Model_Question->loadAnswerData() #2 /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/lib/model/QuizMaster_Model_Model.php(28): QuizMaster_Model_Question->processFieldsDuringModelSet(Array) #3 /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/lib/model/QuizMaster_Model_Model.php(15): QuizMaster_Model_Model->setModelByID(1943) #4 /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/templates/reports/score-que in /srv/users/serverpilot/apps/pro-quiz-demo/public/wp-content/plugins/quizmaster/lib/model/QuizMaster_Model_Question.php on line 299

**Comment by goldhat** [comment]
Resolved, never load questions directly using Question Model, we need to use the QuestionMapper Model fetch() method. Could certainly move that functionality into the Question Model, it's just that there has to be a check of the answer type so the correct question model is loaded that extends the parent Question Model.
